"""Versioned model registry (``models/registry.yaml``).

Each entry pins everything inference needs: classes, preprocessing, the temperature, the
deferral threshold, the conformal threshold, the weights' SHA-256 and the run it came from.
The GUI's model list is read from here, so every choice the user sees maps to a real,
verified model. Entries are created from completed runs with ``spermtriage register``.
"""

from __future__ import annotations

import json
import shutil
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

import yaml

from spermtriage.config import project_root
from spermtriage.data.download import IntegrityError
from spermtriage.repro import sha256_file

INTENDED_USE = (
    "Research decision support only. Not a medical device; not for diagnosis or treatment "
    "decisions. Every 'Refer to expert' result must be reviewed by a qualified person."
)


@dataclass
class SelectivePolicy:
    score: str  # "msp" (temperature-scaled maximum softmax probability)
    threshold: float | None  # accept when score >= threshold; None = refer everything
    target_accuracy: float
    delta: float
    method: str  # "sgr" (certified) or "plugin" (uncertified)
    certified: bool


@dataclass
class ConformalPolicy:
    method: str  # "lac" | "aps" | "lac_classwise"
    alpha: float
    threshold: list[float | None]  # one value, or one per class for lac_classwise


@dataclass
class RegisteredModel:
    id: str
    version: str
    dataset: str
    classes: list[str]
    backbone: str
    timm_name: str
    mode: str  # "finetune" or "linear_probe"
    image_size: int
    preprocessing: str
    temperature: float
    selective: SelectivePolicy
    conformal: ConformalPolicy
    weights_path: str  # relative to the project root
    weights_sha256: str
    source_run: str
    source_commit: str
    metrics: dict[str, Any] = field(default_factory=dict)
    intended_use: str = INTENDED_USE

    @property
    def display_name(self) -> str:
        return f"{self.dataset.upper()} - {self.backbone} ({self.mode}) v{self.version}"

    def resolved_weights(self, root: Path | None = None) -> Path:
        return (root or project_root()) / self.weights_path

    def verify_weights(self, root: Path | None = None) -> Path:
        path = self.resolved_weights(root)
        if not path.exists():
            raise FileNotFoundError(
                f"Weights for '{self.id}' not found at {path}. Download the release assets "
                "(see README, 'Pretrained models') or re-create them with `spermtriage register`."
            )
        digest = sha256_file(path)
        if digest != self.weights_sha256:
            raise IntegrityError(
                f"Weights for '{self.id}' have SHA-256 {digest}, expected {self.weights_sha256}"
            )
        return path

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> RegisteredModel:
        d = dict(d)
        d["selective"] = SelectivePolicy(**d["selective"])
        d["conformal"] = ConformalPolicy(**d["conformal"])
        return cls(**d)


@dataclass
class ModelRegistry:
    models: list[RegisteredModel]
    path: Path | None = None

    @classmethod
    def load(cls, path: str | Path) -> ModelRegistry:
        path = Path(path)
        if not path.exists():
            return cls([], path)
        raw = yaml.safe_load(path.read_text()) or {}
        return cls([RegisteredModel.from_dict(m) for m in raw.get("models", [])], path)

    def save(self, path: str | Path | None = None) -> Path:
        target = Path(path or self.path or project_root() / "models" / "registry.yaml")
        target.parent.mkdir(parents=True, exist_ok=True)
        header = "# Generated by `spermtriage register`. Edit the source run, not this file.\n"
        body = yaml.safe_dump(
            {"models": [asdict(m) for m in self.models]}, sort_keys=False, allow_unicode=True
        )
        target.write_text(header + body)
        return target

    def get(self, model_id: str) -> RegisteredModel:
        for m in self.models:
            if m.id == model_id:
                return m
        raise KeyError(f"Model '{model_id}' is not in the registry. Available: {self.ids()}")

    def ids(self) -> list[str]:
        return [m.id for m in self.models]

    def upsert(self, entry: RegisteredModel) -> None:
        self.models = [m for m in self.models if m.id != entry.id] + [entry]


def register_run(
    run_path: Path,
    version: str,
    conformal_method: str = "lac",
    alpha: float = 0.10,
    registry_path: Path | None = None,
    metrics: dict[str, Any] | None = None,
) -> RegisteredModel:
    """Create a registry entry from a completed, evaluated run and copy its weights."""
    root = project_root()
    run_cfg = yaml.safe_load((run_path / "config.yaml").read_text())
    posthoc = json.loads((run_path / "posthoc.json").read_text())
    prov = json.loads((run_path / "provenance.json").read_text())
    mode = run_cfg["train"]["mode"]
    src = run_path / ("model.pt" if mode == "finetune" else "head.npz")
    model_id = f"{run_cfg['dataset']}-{run_cfg['model_id']}-fold{run_cfg['fold']}"
    dest = root / "models" / "weights" / f"{model_id}-v{version}{src.suffix}"
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)
    sel = posthoc["selective"]["msp"]["sgr"]
    conf = posthoc["conformal"][f"{conformal_method}@{alpha:.2f}"]
    entry = RegisteredModel(
        id=model_id,
        version=version,
        dataset=run_cfg["dataset"],
        classes=list(run_cfg["classes"]),
        backbone=run_cfg["backbone"],
        timm_name=run_cfg["timm_name"],
        mode=mode,
        image_size=int(run_cfg["train"]["image_size"]),
        preprocessing=(
            "RGB; pad to square by edge replication; bilinear resize to "
            f"{run_cfg['train']['image_size']} px; backbone's own mean/std normalisation"
        ),
        temperature=float(posthoc["temperature"]),
        selective=SelectivePolicy(
            score="msp",
            threshold=sel["threshold"],
            target_accuracy=posthoc["selective"]["target_accuracy"],
            delta=posthoc["selective"]["delta"],
            method="sgr",
            certified=bool(sel["certified"]),
        ),
        conformal=ConformalPolicy(
            method=conformal_method, alpha=alpha, threshold=conf["threshold"]
        ),
        weights_path=dest.relative_to(root).as_posix(),
        weights_sha256=sha256_file(dest),
        source_run=run_path.relative_to(root).as_posix(),
        source_commit=prov.get("code_commit", prov["git_commit"]),
        metrics=metrics or {},
    )
    registry = ModelRegistry.load(registry_path or root / "models" / "registry.yaml")
    registry.upsert(entry)
    registry.save()
    return entry
