"""Command-line interface: ``spermtriage <command>``.

Commands
--------
data      download, verify, hash and split the official datasets
train     run an experiment grid (dataset x model x fold)
evaluate  post-hoc calibration, selective prediction and conformal analysis per run
report    aggregate all runs into results/summary.csv, statistical tests and figures
predict   classify images with a registered model (same Predictor the GUI uses)
gui       launch the desktop application
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from spermtriage.config import project_root


def _cmd_data(args: argparse.Namespace) -> int:
    from spermtriage.config import SplitConfig, load_dataset_spec
    from spermtriage.data.download import fetch_dataset
    from spermtriage.data.integrity import (
        build_manifest,
        integrity_report,
        manifest_path,
    )
    from spermtriage.data.splits import check_no_leakage, make_splits, splits_path

    reports = []
    for name in args.dataset:
        spec = load_dataset_spec(name)
        image_dir = fetch_dataset(spec)
        manifest = build_manifest(spec, image_dir)
        path = manifest_path(name)
        path.parent.mkdir(parents=True, exist_ok=True)
        manifest.to_csv(path, index=False)
        kept = manifest[manifest["status"] == "ok"].reset_index(drop=True)
        cfg = SplitConfig(seed=args.seed)
        splits = make_splits(kept, cfg)
        check_no_leakage(splits, kept)
        spath = splits_path(name, cfg.version)
        spath.parent.mkdir(parents=True, exist_ok=True)
        splits.to_csv(spath, index=False)
        report = integrity_report(spec.display_name, manifest)
        reports.append(report.as_markdown())
        print(report.as_markdown(), "\n")
    out = project_root() / "data" / "INTEGRITY.md"
    out.write_text(
        "# Data integrity report\n\nGenerated by `spermtriage data`. Do not edit by hand.\n\n"
        + "\n\n".join(reports)
        + "\n"
    )
    return 0


def _cmd_train(args: argparse.Namespace) -> int:
    from spermtriage.training.runner import run_experiment

    run_experiment(args.experiment, args.dataset, args.model, args.fold, force=args.force)
    return 0


def _cmd_evaluate(args: argparse.Namespace) -> int:
    from spermtriage.evaluation.posthoc import evaluate_all

    evaluate_all(args.experiment, force=args.force)
    return 0


def _cmd_report(args: argparse.Namespace) -> int:
    from spermtriage.reporting.report import build_report

    build_report(args.experiment)
    return 0


def _cmd_predict(args: argparse.Namespace) -> int:
    from spermtriage.inference.model_registry import ModelRegistry
    from spermtriage.inference.predictor import Predictor

    registry = ModelRegistry.load(args.registry)
    predictor = Predictor.from_registry(registry, args.model)
    paths: list[Path] = []
    for p in args.images:
        path = Path(p)
        paths += sorted(q for q in path.iterdir() if q.is_file()) if path.is_dir() else [path]
    rows = predictor.predict_paths(paths)
    if args.csv:
        predictor.write_csv(rows, Path(args.csv))
    for row in rows:
        print(json.dumps(row.to_json_dict()))
    return 0


def _cmd_gui(args: argparse.Namespace) -> int:
    from spermtriage.app.main import run_app

    return run_app(args.registry)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="spermtriage", description=__doc__.split("\n")[0])
    parser.add_argument("-v", "--verbose", action="store_true")
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("data", help="download, verify, hash and split datasets")
    p.add_argument("--dataset", nargs="+", default=["hushem", "smids"])
    p.add_argument("--seed", type=int, default=20251005)
    p.set_defaults(func=_cmd_data)

    default_exp = str(project_root() / "configs" / "experiments" / "main.yaml")
    p = sub.add_parser("train", help="run an experiment grid")
    p.add_argument("--experiment", default=default_exp)
    p.add_argument("--dataset", nargs="*")
    p.add_argument("--model", nargs="*")
    p.add_argument("--fold", nargs="*", type=int)
    p.add_argument("--force", action="store_true", help="re-run completed runs")
    p.set_defaults(func=_cmd_train)

    p = sub.add_parser("evaluate", help="post-hoc uncertainty analysis per run")
    p.add_argument("--experiment", default="main")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=_cmd_evaluate)

    p = sub.add_parser("report", help="aggregate runs into tables and figures")
    p.add_argument("--experiment", default="main")
    p.set_defaults(func=_cmd_report)

    default_registry = str(project_root() / "models" / "registry.yaml")
    p = sub.add_parser("predict", help="classify images with a registered model")
    p.add_argument("images", nargs="+", help="image files or folders")
    p.add_argument("--model", required=True, help="model id from the registry")
    p.add_argument("--registry", default=default_registry)
    p.add_argument("--csv", help="also write results to this CSV file")
    p.set_defaults(func=_cmd_predict)

    p = sub.add_parser("gui", help="launch the desktop application")
    p.add_argument("--registry", default=default_registry)
    p.set_defaults(func=_cmd_gui)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    return int(args.func(args))


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
